$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'BM0'
  app.frameworks += ['CoreAudio', 'AVFoundation']
end
